language: crystal

crystal:
  - latest

script:
  - crystal spec
  - crystal tool format --check
  - bin/ameba
  - crystal docs

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  project_name: geojson
  local_dir: docs
  on:
    branch: master
